export let Constants = {
  COMET_START_ANIMATE: 'COMET_START_ANIMATE',
  COMET_STOP_ANIMATE: 'COMET_STOP_ANIMATE',
  COMET_SET_POSITION: 'COMET_SET_POSITION',
  COMET_BLUR: 'COMET_BLUR',
  COMET_UNBLUR: 'COMET_UNBLUR',
  OPEN_IMAGE: 'OPEN_IMAGE',
  CLOSE_IMAGE: 'CLOSE_IMAGE',
  EXPLODE: 'EXPLODE'
}
